# Generated by Django 5.1.2 on 2025-03-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterbook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDashboard',
        ),
        migrations.RemoveField(
            model_name='waterbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='WaterBooking',
        ),
    ]
