# Generated by Django 5.1.2 on 2025-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbook', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbooking',
            name='number_of_tins',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
